version: "3.9"

services:
  calculator:
    container_name: calculator-app
    image: pial847/calculator-app:1.0.0
    ports:
      - "5000:5000"
    networks:
      - calculator-net

networks:
  calculator-net:
    driver: bridge
